version: '3.2'
services:
  elastic:
    container_name: elastic
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    hostname: elastic
    environment:
       - node.name=elastic
       - cluster.name=elastic-docker-cluster
       - discovery.seed_hosts=elastic02,elastic03
       - cluster.initial_master_nodes=elastic,elastic02
       - bootstrap.memory_lock=true
       - ES_JAVA_OPTS= -Xms1G -Xmx1G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  elastic02:
    container_name: elastic02
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    hostname: elastic02
    environment:
       - node.name=elastic02
       - cluster.name=elastic-docker-cluster
       - discovery.seed_hosts=elastic,elastic03
       - cluster.initial_master_nodes=elastic,elastic02,elastic03
       - bootstrap.memory_lock=true
       - ES_JAVA_OPTS= -Xms1G -Xmx1G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elastic02:/usr/share/elasticsearch/data
    networks:
      - elastic

  elastic03:
    container_name: elastic03
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    hostname: elastic03
    environment:
       - node.name=elastic03
       - cluster.name=elastic-docker-cluster
       - discovery.seed_hosts=elastic,elastic02
       - cluster.initial_master_nodes=elastic,elastic02,elastic03
       - bootstrap.memory_lock=true
       - ES_JAVA_OPTS= -Xms1G -Xmx1G
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elastic03:/usr/share/elasticsearch/data
    networks:
      - elastic

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - ./logstash/config/:/usr/share/logstash/config/        
      - ./logstash/conf.d/:/usr/share/logstash/etc/logstash/conf.d/
      - ./logstash/conf.d/patterns/:/usr/share/logstash/etc/logstash/conf.d/patterns/
      - ./logstash/conf.d/templates/:/usr/share/logstash/etc/logstash/conf.d/templates/
      - ./logstash/conf.d/databases/:/usr/share/logstash/etc/logstash/conf.d/databases/
      - /usr/share/GeoIP/:/usr/share/logstash/GeoIP/
    ports:
      - "5000:5000"
      - "9600:9600"
      - "5140:5140/udp"
    environment:
      LS_JAVA_OPTS: -Xmx1G -Xms1G
    networks:
      - elastic
    depends_on:
      - elastic

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - logstash

volumes:
  elastic:
    driver: local
  elastic02:
    driver: local
  elastic03:
    driver: local

networks:
  elastic:
    driver: bridge
